# Generated by Django 5.2.5 on 2025-08-09 05:17

import avatar_processor.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(help_text='Original uploaded image', upload_to=avatar_processor.models.upload_to_original, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('original_filename', models.CharField(help_text='Original filename', max_length=255)),
                ('processed_image', models.ImageField(blank=True, help_text='Processed avatar image', null=True, upload_to=avatar_processor.models.upload_to_processed)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('was_cropped', models.BooleanField(default=False)),
                ('background_removed', models.BooleanField(default=False)),
                ('output_width', models.PositiveIntegerField(blank=True, null=True)),
                ('output_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_original', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('file_size_processed', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processed Avatar',
                'verbose_name_plural': 'Processed Avatars',
                'ordering': ['-created_at'],
            },
        ),
    ]
